
const tableConfigs = window.TABLE_CONFIGS || [window.TABLE_CONFIG];
let currentConfig = tableConfigs[0];
const suits = ['♠','♥','♦','♣'];
const ranks = ['A','2','3','4','5','6','7','8','9','10','J','Q','K'];
let shoe=[], discard=[], dealer={cards:[]}, players=[], humanIndex=0, activeHand=0, handInProgress=false, offerInsurance=false, log=[];
const BANKROLL_START = 1000;
function bankrollKey(){ return 'blackjackBankroll_' + (currentConfig.title || 'table').replace(/\W+/g,'_'); }
function getSavedBankroll(){ const v = Number(localStorage.getItem(bankrollKey())); return Number.isFinite(v) ? v : BANKROLL_START; }
function saveBankroll(v){ localStorage.setItem(bankrollKey(), String(Math.max(0, Math.round(v)))); }
function resetBankroll(){ saveBankroll(BANKROLL_START); if(players[0]) players[0].bankroll = BANKROLL_START; logMsg('Bankroll reset back to $1000.'); render(); }
function cardValue(rank){ if(rank==='A') return 11; if(['K','Q','J'].includes(rank)) return 10; return Number(rank); }
function handValue(cards){ let total=cards.reduce((s,c)=>s+cardValue(c.rank),0); let aces=cards.filter(c=>c.rank==='A').length; while(total>21&&aces){total-=10;aces--} return {total,soft:aces>0}; }
function isBlackjack(cards){ return cards.length===2 && handValue(cards).total===21; }
function canSplit(hand){ return hand.cards.length===2 && hand.cards[0].rank===hand.cards[1].rank && !hand.splitDone; }
function totalHumanBet(){ return (players[0]?.hands || []).reduce((sum,h)=>sum + Number(h.bet || 0) + Number(h.insurance || 0), 0); }
function canDouble(hand){ return hand && hand.cards.length===2 && !hand.stood && !hand.busted && !hand.doubled && !hand.splitAces && !isBlackjack(hand.cards); }
function money(n){return '$'+Number(n).toFixed(0)}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function buildShoe(){ shoe=[]; discard=[]; for(let d=0;d<currentConfig.decks;d++){ for(const s of suits){ for(const r of ranks){ shoe.push({rank:r,suit:s}); } } } shuffle(shoe); logMsg(`New 6 deck regular shoe started. Cut card at ${Math.round(currentConfig.penetration*100)}% penetration.`); render(); }
function draw(faceDown=false){ if(shoe.length===0) buildShoe(); const c=shoe.pop(); c.faceDown=faceDown; return c; }
function discardCards(cards){ for(const c of cards){ discard.push({...c,faceDown:false}); } }
function maybeShuffle(){ const total=currentConfig.decks*52; const dealt=total-shoe.length; if(dealt/total>=currentConfig.penetration && !handInProgress){ logMsg(`Cut card reached. Shoe reshuffled after ${dealt} cards.`); buildShoe(); } }
function newPlayers(){ const seats=Number(document.getElementById('seatSelect')?.value||5); const savedBankroll = players[0]?.bankroll ?? getSavedBankroll(); players=[{name:'You',type:'human',skill:'human',bankroll:savedBankroll,hands:[]}]; const names=['Marty','Dee','Sal','Nina','Vic','Rosa']; const skills=['sub par','average','good','sub par','good','average']; for(let i=0;i<seats;i++){ players.push({name:names[i],type:'ai',skill:skills[i],bankroll:1000,hands:[]}); } }
function dealHand(){ if(handInProgress) return; maybeShuffle(); newPlayers(); const bet=Math.max(5,Number(document.getElementById('betInput').value||25)); if(players[0].bankroll < bet){ logMsg(`You need at least ${money(bet)} to place this bet. Reset the bankroll to $1000 or lower your bet.`); render(); return; } dealer={cards:[]}; for(const p of players){ p.hands=[{cards:[],bet:bet,result:'',stood:false,busted:false,splitDone:false,splitAces:false,doubled:false,insurance:0}]; }
 for(let round=0;round<2;round++){ for(const p of players){ p.hands[0].cards.push(draw()); } dealer.cards.push(draw(round===1)); }
 handInProgress=true; activeHand=0; offerInsurance = dealer.cards[0].rank==='A'; logMsg(`Hand dealt at ${currentConfig.title}. Dealer upcard is ${dealer.cards[0].rank}${dealer.cards[0].suit}.`); if(offerInsurance) logMsg('Insurance is available because dealer is showing an Ace.'); if(dealer.cards[0].rank==='A'){} render(); if(isBlackjack(players[0].hands[0].cards)) stand(); }
function logMsg(m){ log.unshift(m); log=log.slice(0,80); }
function humanHand(){ return players[humanIndex].hands[activeHand]; }
function hit(){ const h=humanHand(); h.cards.push(draw()); const v=handValue(h.cards).total; if(v>21){ h.busted=true; h.result='Bust'; logMsg(`You busted with ${v}.`); nextHumanHand(); } render(); }
function stand(){ humanHand().stood=true; nextHumanHand(); render(); }
function doubleDown(){ const p=players[0], h=humanHand(); if(!canDouble(h)) return; if(totalHumanBet() + h.bet > p.bankroll){ logMsg(`Not enough bankroll to double. You need another ${money(h.bet)} available.`); render(); return; } h.bet *= 2; h.doubled=true; h.cards.push(draw()); const v=handValue(h.cards).total; if(v>21){ h.busted=true; h.result='Bust'; logMsg(`You doubled and busted with ${v}.`); } else { h.stood=true; logMsg(`You doubled to ${money(h.bet)} and received one final card.`); } nextHumanHand(); render(); }
function split(){ const p=players[0], h=humanHand(); if(!canSplit(h)) return; if(totalHumanBet() + h.bet > p.bankroll){ logMsg(`Not enough bankroll to cover another ${money(h.bet)} split bet.`); render(); return; } if(h.cards[0].rank==='A'){ logMsg('Split Aces are allowed, but no extra/even bet control or further split action is available on Aces in this version.'); }
 const c2=h.cards.pop(); h.splitDone=true; const isAces=h.cards[0].rank==='A'; h.splitAces=isAces; const newHand={cards:[c2],bet:h.bet,result:'',stood:false,busted:false,splitDone:true,splitAces:isAces,doubled:false,insurance:0}; h.cards.push(draw()); newHand.cards.push(draw()); p.hands.splice(activeHand+1,0,newHand); logMsg('You split duplicate cards into two equal bet hands.'); render(); }
function insurance(){ if(!offerInsurance) return; const h=players[0].hands[0]; if(h.insurance>0) return; if(players[0].bankroll < (h.bet + h.bet/2)){ logMsg(`Not enough bankroll to cover insurance of ${money(h.bet/2)}.`); render(); return; } h.insurance=h.bet/2; logMsg(`Insurance placed for ${money(h.insurance)}.`); render(); }
function nextHumanHand(){ const p=players[0]; for(let i=0;i<p.hands.length;i++){ if(!p.hands[i].stood && !p.hands[i].busted){ activeHand=i; return; } } aiTurns(); dealerTurn(); settle(); handInProgress=false; offerInsurance=false; discardAll(); maybeShuffle(); render(); }
function aiDecision(hand, dealerUp, skill){ const v=handValue(hand.cards); if(skill==='sub par'){ if(Math.random()<.18) return 'badHit'; return v.total<15?'hit':'stand'; }
 if(skill==='average') return v.total<16 || (v.soft && v.total<18) ? 'hit':'stand';
 const upVal=cardValue(dealerUp.rank); if(v.total<=11) return 'hit'; if(v.soft && v.total<=17) return 'hit'; if(v.total===12) return (upVal>=4&&upVal<=6)?'stand':'hit'; if(v.total>=13&&v.total<=16) return upVal<=6?'stand':'hit'; return 'stand'; }
function aiTurns(){ for(const p of players.slice(1)){ for(const h of p.hands){ while(true){ const decision=aiDecision(h,dealer.cards[0],p.skill); if(decision==='hit'||decision==='badHit'){ h.cards.push(draw()); if(handValue(h.cards).total>21){h.busted=true;h.result='Bust'}; if(h.busted) break; } else break; } } } logMsg('Computer players completed their hands.'); }
function dealerTurn(){ dealer.cards.forEach(c=>c.faceDown=false); while(true){ const v=handValue(dealer.cards); if(v.total<17 || (v.total===17 && v.soft && currentConfig.dealerHitsSoft17)){ dealer.cards.push(draw()); } else break; } logMsg(`Dealer stands with ${handValue(dealer.cards).total}.`); }
function settle(){ const dv=handValue(dealer.cards).total; const dealerBJ=isBlackjack(dealer.cards); for(const p of players){ for(const h of p.hands){ const hv=handValue(h.cards).total; let delta=0, txt=''; if(h.insurance){ delta += dealerBJ ? h.insurance*2 : -h.insurance; }
 if(h.busted){ delta-=h.bet; txt='Lost'; }
 else if(isBlackjack(h.cards)&&!dealerBJ){ delta += h.bet*currentConfig.blackjackPayout; txt=`Blackjack pays ${currentConfig.blackjackPayout===1.5?'3:2':'6:5'}`; }
 else if(dealerBJ&&!isBlackjack(h.cards)){ delta-=h.bet; txt='Lost to dealer blackjack'; }
 else if(dv>21 || hv>dv){ delta+=h.bet; txt='Won'; }
 else if(hv<dv){ delta-=h.bet; txt='Lost'; } else { txt='Push'; }
 p.bankroll+=delta; if(p.type==='human') saveBankroll(p.bankroll); h.result=`${txt} (${delta>=0?'+':''}${money(delta)})`; } } logMsg('Round settled. Played cards moved to discard tray.'); }
function discardAll(){ for(const p of players){ for(const h of p.hands) discardCards(h.cards); } discardCards(dealer.cards); }
function renderCard(c, mini=false){ if(c.faceDown) return `<div class="card ${mini?'mini-card':''} back">?</div>`; const red=c.suit==='♥'||c.suit==='♦'; return `<div class="card ${mini?'mini-card':''} ${red?'red':''}">${c.rank}${c.suit}</div>`; }
function render(){ document.title=currentConfig.title; document.querySelector('h1').textContent=currentConfig.title; document.getElementById('rulesList').innerHTML=[['Blackjack payout',currentConfig.blackjackPayout===1.5?'3:2':'6:5'],['Decks','6 deck regular shoe'],['Penetration',`${Math.round(currentConfig.penetration*100)}% before shuffle`],['Dealer rule','Hits soft 17'],['Splits','Duplicate ranks allowed'],['Split bets','Equal bet except Aces'],['Double down','Allowed on first two cards when bankroll can cover it'],['Insurance','Offered on dealer Ace upcard']].map(r=>`<div class="rule"><span>${r[0]}</span><span>${r[1]}</span></div>`).join('');
 const total=currentConfig.decks*52, remaining=shoe.length, dealt=total-remaining; document.getElementById('shoeFill').style.width=`${remaining/total*100}%`; document.getElementById('shoeStats').innerHTML=`Cards remaining: <b>${remaining}</b><br>Cards seen/dealt: <b>${dealt}</b><br>Discard tray: <b>${discard.length}</b><br>Cut card: <b>${Math.round(currentConfig.penetration*100)}%</b>`; document.getElementById('discardTray').innerHTML=discard.slice(-80).reverse().map(c=>renderCard(c,true)).join('')||'<span class="muted">No discards yet.</span>';
 document.getElementById('dealerCards').innerHTML=dealer.cards.map(c=>renderCard(c)).join(''); const visible=dealer.cards.filter(c=>!c.faceDown); document.getElementById('dealerScore').textContent=dealer.cards.length?`Value: ${handValue(visible).total}${dealer.cards.some(c=>c.faceDown)?' plus hole card':''}`:'';
 document.getElementById('playersArea').innerHTML=players.map((p,pi)=>`<div class="player ${pi===0&&handInProgress?'active':''}"><h3><span>${p.name}</span><span>${p.skill}</span></h3><div class="bankroll">Bankroll ${money(p.bankroll)}</div>${p.hands.map((h,hi)=>`<div class="hand"><div>Hand ${hi+1} · Bet ${money(h.bet)} · ${handValue(h.cards).total}</div><div class="cards">${h.cards.map(c=>renderCard(c,true)).join('')}</div><div class="result">${h.result||''}</div></div>`).join('')}</div>`).join('');
 document.getElementById('messageLog').innerHTML=log.map(m=>`<div>${m}</div>`).join('');
 const h=players[0]?.hands?.[activeHand]; document.getElementById('hitBtn').disabled=!handInProgress||!h||h.busted||h.stood; document.getElementById('standBtn').disabled=!handInProgress||!h||h.busted||h.stood; document.getElementById('doubleBtn').disabled=!handInProgress||!h||!canDouble(h)||totalHumanBet()+h.bet>players[0].bankroll; document.getElementById('splitBtn').disabled=!handInProgress||!h||!canSplit(h); document.getElementById('insuranceBtn').disabled=!handInProgress||!offerInsurance||(players[0]?.hands?.[0]?.insurance>0);
 const sw=document.getElementById('tableSwitch'); if(tableConfigs.length>1){ sw.innerHTML=tableConfigs.map((c,i)=>`<button data-i="${i}">${c.blackjackPayout===1.5?'3:2 Normal':'6:5 Poor'} Table</button>`).join(''); sw.querySelectorAll('button').forEach(b=>b.onclick=()=>{currentConfig=tableConfigs[Number(b.dataset.i)]; log=[]; newPlayers(); buildShoe();}); } }
document.getElementById('newShoeBtn').onclick=buildShoe; document.getElementById('resetBankrollBtn').onclick=resetBankroll; document.getElementById('dealBtn').onclick=dealHand; document.getElementById('hitBtn').onclick=hit; document.getElementById('standBtn').onclick=stand; document.getElementById('doubleBtn').onclick=doubleDown; document.getElementById('splitBtn').onclick=split; document.getElementById('insuranceBtn').onclick=insurance; document.getElementById('seatSelect').onchange=()=>{if(!handInProgress){newPlayers();render();}}; newPlayers(); buildShoe();
